### ISSUE TITLE
bundle.js:162 WebSocket connection to 'ws://localhost:33012/gateway' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by saytree** [Terkwood/BUGOUT#471]
I tried to apply the source to the server, but the above error occurred. How do I fix it?

**Comment by Terkwood** [comment]
Hi, right now there's no good way to start KataGo and play it locally, on your own machine. The build process is pretty specialized and fragile. Eventually I'll want to improve it, but it's a significant chunk of work, so I can't offer an estimate about when it can be delivered. 

That said, the _multiplayer_ functionality does work on a local dev's machine, although I need to update the docs slightly to address the issue you're facing. I'll post here once that's completed. 

I'm not sure this will be very helpful, as I'm assuming that the KataGo play option is what sparked your interest.

**Comment by saytree** [comment]
Thank you for the reply.

I am Korean and I am a beginner programmer who is very interested in
baduk(Go).

We hope to be a better project in the future and we will continue to pay
attention.

Thank you.

>

**Comment by Terkwood** [comment]
Great! If you just want to play KataGo AI on your own computer, I recommend KaTrain  https://github.com/sanderland/katrain

**Comment by Terkwood** [comment]
Apologies for the slow response!

I just merged #477, which provides an admin script that will create the necessary directory structure on your machine, as well as configure the `Caddyfile` required by the reverse-proxy component (this lets your web browser talk to the backend services).

[See the updated README](https://github.com/Terkwood/BUGOUT#getting-started-with-development) for the instructions.

So far I've only run this system on Mac OS X and Linux, so if you're in a Windows environment.... Well, I'm not sure exactly how bad that'll be. 👼🏻

**Comment by Terkwood** [comment]
Clarified some of the hidden pitfalls of running this system, locally.  Please see the updated README if interested!
