### ISSUE TITLE
about territory  calculation

### ISSUE THREAD

**Issue by saytree** [Terkwood/BUGOUT#472]
I would like to make the calculation of the house more explicit and accurate.

Especially those for dead stones are difficult to deal with clearly.

**Comment by Terkwood** [comment]
Right now the project uses  Sabaki's implementation for dead stones & estimates : https://github.com/SabakiHQ/deadstones

**Comment by Terkwood** [comment]
I think the biggest question here is, "how do we improve the calculation of dead stones?"

The Sabaki/dead stones lib uses Monte Carlo 

What approaches are used by   other implementations of Go  ?
